% Create a rectangularArray with dipole element.
% Generated by MATLAB(R) 9.13 and Antenna Toolbox 5.3.
% Generated on: 06-Feb-2024 15:03:08

%% Array Properties 

SubObject = design(dipole, 2000*1e6);
arrayObject = design(rectangularArray('Element', SubObject), 2000*1e6, SubObject);
arrayObject.Size = [4, 2];

%% Array Analysis 
% Show for rectangularArray
figure;
show(arrayObject) 
% Layout for rectangularArray
figure;
layout(arrayObject) 
% Azimuth for rectangularArray
plotFrequency = 2000*1e6; azRange = 0:5:360; termination = 50;
figure;
pattern(arrayObject, plotFrequency, azRange, 0, 'Termination', termination);
% Elevation for rectangularArray
plotFrequency = 2000*1e6; elRange = 0:5:360; termination = 50;
figure;
pattern(arrayObject, plotFrequency, 0, elRange, 'Termination', termination);
% Pattern for rectangularArray
plotFrequency = 2000*1e6; termination = 50;
figure;
pattern(arrayObject, plotFrequency, 'Termination', termination); 

