clear;
f_c = 1880e6;
c = physconst("LightSpeed");
lambda = c/f_c;
D = 2;
F = 1.2;
D_lambda = D/lambda;
p = design(reflectorParabolic,f_c);
p.Radius = D/2;
p.FocalLength = F;
p.Tilt = 45;
p.TiltAxis = [0 1 0];
figure;
show(p);
m = memoryEstimate(p,f_c);
az = -180:1:180;
el = -180:1:180;
figure;
pattern(p,f_c,az,el);