view([0 90]);
s.EdgeColor = 'none';
cb = colorbar;
cb.Label.String = 'Interference Power (dBW)';
clim([-330 0]);
f = gcf;
a = gca;
f.Units = 'inches';
f.Position = [6 6 2.5 1.5];
a.FontName = 'Times New Roman';
a.FontSizeMode = 'manual';
a.FontSize = 9;
a.LabelFontSizeMultiplier = 1;
grid on;
a.GridAlpha = 0.4;
a.Colormap = colormap(jet(256));
xlabel('Longitude Distance (m)');
ylabel('Latitude Distance (m)');
t = text(-35,35,"RAS");
t.FontName = 'Times New Roman';
t.Color = 'yellow';
t = text(40,-155,"gNB");
t.FontName = 'Times New Roman';
t.Color = 'yellow';
hold on;
plot(40,-110,'ob');
plot(0,0,'og');

% view([0 90]);
% s.EdgeColor = 'none';
% xlabel('Longitude Distance (m)');
% ylabel('Latitude Distance (m)');
% t = text(-35,35,"RAS");
% t.FontName = 'Times New Roman';
% t = text(40,-155,"gNB");
% t.FontName = 'Times New Roman';
% hold on;
% plot(40,-110,'ob');
% plot(0,0,'or');